#secrets
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  mysql-root-password: rootpass
  mysql-password: quthpass
  jwt-secret-key: super-secret-key-change-in-production
---
#config
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: authdb
  MYSQL_USER: auth
  MONGO_URI: mongodb://mongodb:27017
  MONGO_DB_NAME: fundb
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  GANACHE_URL: http://ganache:8545
---
#persistent data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
#mysql
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
---
#mongo
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
#redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
---
#auth-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth_service:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: mysql-password
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MYSQL_DATABASE
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret-key
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: LoadBalancer
  selector:
    app: auth-service
  ports:
    - port: 5001
      targetPort: 5000

---
#employee-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
        - name: employee-service
          image: employee_service
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret-key
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_DB_NAME
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: employee-service
spec:
  type: LoadBalancer
  selector:
    app: employee-service
  ports:
    - port: 5002
      targetPort: 5000

---
#director-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: director-service
spec:
  selector:
    matchLabels:
      app: director-service
  template:
    metadata:
      labels:
        app: director-service
    spec:
      containers:
        - name: director-service
          image: director_service:2
          imagePullPolicy: IfNotPresent
          env:
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: jwt-secret-key
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_URI
            - name: MONGO_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MONGO_DB_NAME
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REDIS_PORT
            - name: GANACHE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GANACHE_URL
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: director-service
spec:
  type: LoadBalancer
  selector:
    app: director-service
  ports:
    - port: 5003
      targetPort: 5000

---
#blockchain
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganache
spec:
  selector:
    matchLabels:
      app: ganache
  template:
    metadata:
      labels:
        app: ganache
    spec:
      containers:
        - name: ganache
          image: trufflesuite/ganache-cli
          args: ["--deterministic", "--accounts", "10", "--host", "0.0.0.0"]
          ports:
            - containerPort: 8545
---
apiVersion: v1
kind: Service
metadata:
  name: ganache
spec:
  type: LoadBalancer
  selector:
    app: ganache
  ports:
    - port: 8545
      targetPort: 8545
